### ISSUE TITLE
Error inliers

### ISSUE THREAD

**Issue by jmiturre** [francofrolla/mapaderindes#4]
Franco, el script da error en el calculo de inliers. Probe con todas las versiones, inclusive con la 1.3 que subiste hace un rato. 
Te adjunto .log y captura.
El archivo que estoy usando es el mapa de prueba que cargaste vos
[LOG.txt](https://github.com/francofrolla/mapaderindes/files/7946028/LOG.txt)

[
![imagen_2022-01-26_192217](https://user-images.githubusercontent.com/98483908/151256952-71e4d41a-2fb5-4df3-ad92-363583ff7de6.png)
](url)

**Comment by jmiturre** [comment]
Solucionado instalando R v 3.6.2.

**Comment by francofrolla** [comment]
Gracias Juan. Es un conflicto de paquetes a mi entender, podes hacer un
sessionInfo() a tu R??. Voy a tratar de solucionarlo para versiones de R >
4.

Saludos.

**Comment by jmiturre** [comment]
Gracias a vos por la herramienta Franco! Me uní al grupo de Telegram, cualquier cosa que necesites avisa.

> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Argentina.1252  LC_CTYPE=Spanish_Argentina.1252   
[3] LC_MONETARY=Spanish_Argentina.1252 LC_NUMERIC=C                      
[5] LC_TIME=Spanish_Argentina.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.2

**Comment by francofrolla** [comment]
@jmiturre pude resolver el erro cambiando el paquete "spdep" que se instala por dafault por la version "1.1.8", lo adjunte al git. Se debe descomprimir y en la libreria de R borrar el que esta y pegar ese.. 
Saludos.

**Comment by jmiturre** [comment]
> @jmiturre pude resolver el erro cambiando el paquete "spdep" que se instala por dafault por la version "1.1.8", lo adjunte al git. Se debe descomprimir y en la libreria de R borrar el que esta y pegar ese.. Saludos.

Buenisimo, mañana actualizo R y lo pruebo Franco! Saludos
